version: 2

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  reviewers:
    - "ghickman"
    - "inglesp"
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  reviewers:
    - "ghickman"
    - "inglesp"
  open-pull-requests-limit: 10
