[tool.coverage.run]
branch = true
omit = [
  "opencodelists/asgi.py",
  "opencodelists/django_test_runner.py",
  "opencodelists/settings.py",
  "opencodelists/wsgi.py",
]

[tool.coverage.report]
skip_covered = true

[tool.coverage.html]

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true
skip_glob = [".direnv", "*migrations*", "tmp", ".venv", "coding_systems/snomedct/parser_utils/*"]
known_third_party = ["antlr4", "bleach", "crispy_forms", "debug_toolbar", "django", "fabric", "hypothesis", "lxml", "markdown2", "openpyxl", "pytest", "rest_framework", "sentry_sdk", "structlog"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "opencodelists.settings"
addopts = "--tb=native --ignore=node_modules"
