[tool.black]
exclude = '''
(
  /(
      \.git         # exclude a few common directories in the
    | \.direnv
    | \.venv
    | venv
  )/
)
'''

[tool.coverage.run]
branch = true
omit = [
  "opencodelists/asgi.py",
  "opencodelists/django_test_runner.py",
  "opencodelists/settings.py",
  "opencodelists/wsgi.py",
]

[tool.coverage.report]
skip_covered = true

[tool.coverage.html]

[tool.isort]
profile = "black"
lines_after_imports = 2
skip_glob = [".direnv", "*migrations*", "tmp", ".venv", "coding_systems/snomedct/parser_utils/*"]
known_third_party = ["antlr4", "bleach", "crispy_forms", "debug_toolbar", "django", "fabric", "hypothesis", "lxml", "markdown2", "openpyxl", "pytest", "rest_framework", "sentry_sdk", "structlog"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "opencodelists.settings"
addopts = "--tb=native --ignore=node_modules --no-migrations"

filterwarnings = [
    "ignore::django.utils.deprecation.RemovedInDjango41Warning:social_django",
]
