[tool.black]
exclude = '''
(
  /(
      \.git         # exclude a few common directories in the
    | migrations    # root of the project
    | \.direnv
    | \.venv
  )/
)
'''

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true
skip_glob = [".direnv", "*migrations*", "tmp", ".venv"]
known_third_party = ["crispy_forms", "django", "fabric", "hypothesis", "pytest", "pytest_django", "sentry_sdk"]

[tool.pytest.ini_options]
env = [
    "DJANGO_SETTINGS_MODULE = opencodelists.settings",
]
