[tool.coverage.run]
branch = true
omit = [
  "opencodelists/asgi.py",
  "opencodelists/django_test_runner.py",
  "opencodelists/settings.py",
  "opencodelists/wsgi.py",
  "staticfiles",
  "*/migrations/*"
]

[tool.coverage.report]
skip_covered = true

[tool.coverage.html]

[tool.isort]
profile = "black"
skip_glob = [".direnv", "*migrations*", "tmp", ".venv", "coding_systems/snomedct/parser_utils/*", "staticfiles"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "opencodelists.settings"
addopts = "--tb=native --ignore=node_modules --no-migrations"

filterwarnings = [
    "ignore::django.utils.deprecation.RemovedInDjango50Warning:rest_framework"
]
